# Generated by Django 5.0.2 on 2024-03-09 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialFundamentalData',
            fields=[
                ('symbol', models.CharField(db_column='Symbol', max_length=10, primary_key=True, serialize=False)),
                ('assettype', models.CharField(db_column='AssetType', max_length=25)),
                ('name', models.CharField(db_column='Name', max_length=45)),
                ('desc', models.CharField(db_column='Desc', max_length=2000)),
                ('cik', models.CharField(db_column='CIK', max_length=10)),
                ('exchange', models.CharField(db_column='Exchange', max_length=10)),
                ('currency', models.CharField(db_column='Currency', max_length=5)),
                ('country', models.CharField(db_column='Country', max_length=20)),
                ('sector', models.CharField(db_column='Sector', max_length=10)),
                ('industry', models.CharField(db_column='Industry', max_length=25)),
                ('address', models.CharField(db_column='Address', max_length=45)),
                ('fiscalyearend', models.CharField(db_column='FiscalYearEnd', max_length=9)),
                ('latestquarter', models.CharField(db_column='LatestQuarter', max_length=10)),
                ('marketcapitalization', models.CharField(db_column='MarketCapitalization', max_length=10)),
                ('ebitda', models.CharField(db_column='EBITDA', max_length=10)),
                ('peration', models.CharField(db_column='PERation', max_length=10)),
                ('pegration', models.CharField(db_column='PEGRation', max_length=10)),
                ('bookvalue', models.CharField(db_column='BookValue', max_length=10)),
                ('dividendpershare', models.CharField(db_column='DividendPerShare', max_length=45)),
                ('divdendyield', models.CharField(db_column='DivdendYield', max_length=10)),
                ('eps', models.CharField(db_column='EPS', max_length=10)),
                ('revenuepersharettm', models.CharField(db_column='RevenuePerShareTTM', max_length=10)),
                ('profitmargin', models.CharField(db_column='ProfitMargin', max_length=10)),
                ('operatingmarginttm', models.CharField(db_column='OperatingMarginTTM', max_length=10)),
                ('returnonassetsttm', models.CharField(db_column='ReturnOnAssetsTTM', max_length=10)),
                ('returnonequityttm', models.CharField(db_column='ReturnOnEquityTTM', max_length=10)),
                ('revenuettm', models.CharField(db_column='RevenueTTM', max_length=10)),
                ('grossprofitttm', models.CharField(db_column='GrossProfitTTM', max_length=10)),
                ('dilutedepsttm', models.CharField(db_column='DilutedEPSTTM', max_length=10)),
                ('quarterlyearningsgrowthyoy', models.CharField(db_column='QuarterlyEarningsGrowthYOY', max_length=10)),
                ('quarterlyrevenuegrowthyoy', models.CharField(db_column='QuarterlyRevenueGrowthYOY', max_length=10)),
                ('analysttargetprice', models.CharField(db_column='AnalystTargetPrice', max_length=10)),
                ('analystratingstrongbuy', models.CharField(db_column='AnalystRatingStrongBuy', max_length=3)),
                ('analystratingbuy', models.CharField(db_column='AnalystRatingBuy', max_length=3)),
                ('analystratinghold', models.CharField(db_column='AnalystRatingHold', max_length=3)),
                ('analystratingsell', models.CharField(db_column='AnalystRatingSell', max_length=3)),
                ('analystratingstrongsell', models.CharField(db_column='AnalystRatingStrongSell', max_length=3)),
                ('trailingpe', models.CharField(db_column='TrailingPE', max_length=10)),
                ('forwardpe', models.CharField(db_column='ForwardPE', max_length=10)),
                ('pricetosalesrationttm', models.CharField(db_column='PriceToSalesRationTTM', max_length=10)),
                ('pricetobookratio', models.CharField(db_column='PriceToBookRatio', max_length=10)),
                ('evtorevenue', models.CharField(db_column='EVToRevenue', max_length=10)),
                ('evtoebitda', models.CharField(db_column='EVToEBITDA', max_length=10)),
                ('beta', models.CharField(db_column='Beta', max_length=10)),
                ('number_52weekhigh', models.CharField(db_column='52WeekHigh', max_length=10)),
                ('number_52weeklow', models.CharField(db_column='52WeekLow', max_length=10)),
                ('number_50daymovingaverage', models.CharField(db_column='50DayMovingAverage', max_length=10)),
                ('number_200daymovingaverage', models.CharField(db_column='200DayMovingAverage', max_length=10)),
                ('sharesoutstanding', models.CharField(db_column='SharesOutstanding', max_length=10)),
                ('dividenddate', models.CharField(db_column='DividendDate', max_length=10)),
                ('exdivedenddate', models.CharField(db_column='ExDivedendDate', max_length=10)),
            ],
            options={
                'db_table': 'financial_fundamental_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LastPull',
            fields=[
                ('date', models.DateField(db_column='Date', primary_key=True, serialize=False)),
                ('time', models.TimeField(db_column='Time')),
            ],
            options={
                'db_table': 'last_pull',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PricingData',
            fields=[
                ('symbol', models.OneToOneField(db_column='Symbol', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dbapp.financialfundamentaldata')),
                ('open', models.CharField(db_column='Open', max_length=10)),
                ('high', models.CharField(db_column='High', max_length=10)),
                ('low', models.CharField(db_column='Low', max_length=10)),
                ('close', models.CharField(db_column='Close', max_length=10)),
                ('volume', models.CharField(db_column='Volume', max_length=10)),
            ],
            options={
                'db_table': 'pricing_data',
                'managed': False,
            },
        ),
    ]